deploy: False
tag: scratch
seed: 0

device : "cuda"
bf16: True
epochs: 1

data:
  n_states: 20
  n_atomic_generators: 4
  min_mixing: 0.05
  max_mixing: 0.1
  tau: 1.0
  atomic_mixing: 0.001
  min_seq_length: 16
  max_seq_length: 32
  max_sample_length: 144
  underspec_ratio: 0.5
  instr_ratio: 0.5
  ex_ratio: 0.0
  max_n_exemplars: 3
  prior_type: 'uniform'
  prior_scale: 1.0
  num_workers: 1
  batch_size: 2

model:
  compile: False
  context_size: 1024
  n_layer: 12
  n_head: 8
  n_embd: 128
  dropout: 0.0
  bias: False
  mlp: True

optimizer:
  learning_rate: 3e-4
  weight_decay: 1e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0

  decay_lr: True
  warmup_iters: 200
  min_lr: 6e-5

log: 
  log_interval: 10
  save_interval: 1000
  free: False


# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
